fix table key bug
idea2app/Idea-React pull request #12
Opened 2022-06-04 07:22 UTC by stevending1st

close #10

2022-06-05 18:24 UTC, TechQuery requested changes
建议给组件加一个 `rowKey={({ xxx }) => xxx}` 的属性给用户生成自定义 `key` 的能力

2022-06-05 18:24 UTC, TechQuery commented on source/IdeaTable.tsx
> +            <tr key={row?.id || index} className="text-center">
https://www.zoo.team/article/vue-index

2022-06-05 18:24 UTC, TechQuery commented on source/IdeaTable.tsx
> +                        <tr key="nodata-tr">
单一子元素无需 `key`

2022-06-06 16:57 UTC, TechQuery requested changes

2022-06-06 16:57 UTC, TechQuery commented on preview/index.html
> +        <script src="https://unpkg.com/prismjs@1.27.0/plugins/autoloader/prism-autoloader.min.js"></script>
顺道升级到最新

2022-06-06 16:57 UTC, TechQuery commented on source/IdeaTable.tsx
> +    rowKey?: string | ((params: T) => string | number);
```suggestion
    rowKey?: (keyof T) | ((params: T) => string | number);
```

2022-06-06 16:57 UTC, TechQuery commented on source/IdeaTable.tsx
> +        const { columns = [], rowKey = (params: T) => params.toString() } =
```suggestion
        const { columns = [], rowKey = (params: T) => JSON.stringify(params) } =
```

2022-06-06 16:57 UTC, TechQuery commented on source/IdeaTable.tsx
> +                key={typeof rowKey === 'string' ? rowKey : rowKey(row)}
```suggestion
                key={typeof rowKey === 'string' ? row[rowKey] : rowKey?.(row)}
```

2022-06-06 17:47 UTC, stevending1st commented on preview/index.html
> +        <script src="https://unpkg.com/prismjs@1.27.0/plugins/autoloader/prism-autoloader.min.js"></script>
哪些需要升级？

2022-06-06 18:41 UTC, TechQuery approved these changes

2022-06-06 18:42 UTC, merged