[polish] IdeaDialog, replace Modal with ModalDialog
idea2app/Idea-React pull request #28
Opened 2022-10-24 13:30 UTC by Soecka

[polish] IdeaDialog, replace Modal with ModalDialog

- Close #25

2022-10-25 14:47 UTC, TechQuery requested changes

2022-10-25 14:47 UTC, TechQuery commented on source/IdeaDialog.tsx
> +    contentClassName?: string;
从 `ModalDialogProps` 上 `Pick` 了再 `extends`

2022-10-25 14:47 UTC, TechQuery commented on source/IdeaDialog.tsx
> +    </>
没感觉你这么写简化了代码结构啊，而且通过 JSX 的 `&&` 来控制也会失去渐变动画

2022-10-25 15:30 UTC, Soecka commented on source/IdeaDialog.tsx
> +    </>
我只把Modal替换成了ModalDIalog，感觉这样会更轻便一些？因为Modal上很多方法都用不上，ModalDialog配合遮罩基本上就能实现Modal最基础的对话框打开和关闭功能；
此处的渐变动画指的是对话框打开和关闭吗？我加了 fade 样式，有一些过渡动画

2022-11-14 19:01 UTC, TechQuery approved these changes

2022-11-15 15:28 UTC, merged