add Vite  & add storybook
idea2app/Idea-React pull request #31
Opened 2023-04-29 15:48 UTC by stevending1st

2023-05-03 13:00 UTC, TechQuery requested changes

2023-05-03 13:00 UTC, TechQuery commented on package.json
> +        "@swc/helpers": "^0.4.14",
不用 SWC 的话就删掉

2023-05-03 13:00 UTC, TechQuery commented on package.json
> +        "@editorjs/paragraph": "^2.9.0",
编辑器组件最少依赖这两个包

2023-05-03 13:00 UTC, TechQuery commented on package.json
> +        "@types/leaflet": "^1.9.0",
地图组件 props 依赖上游包的类型，也不要让用户自己装。

2023-05-03 13:00 UTC, TechQuery commented on package.json
> +        "editorjs-html": "^3.4.2",
这是组件运行依赖的包

2023-05-03 13:00 UTC, TechQuery commented on package.json
> +        "leaflet": "^1.9.3",
运行时依赖挪上去

2023-05-03 13:00 UTC, TechQuery commented on package.json
> +        "mobx-react": "^6.3.1",
组件内部用的状态管理库也要放在运行时依赖

2023-05-03 13:00 UTC, TechQuery commented on package.json
> +        "prismjs": "^1.29.0",
运行时依赖

2023-05-03 13:00 UTC, TechQuery commented on package.json
> +        "react-leaflet": "^3.2.5",
运行时依赖

2023-05-03 13:00 UTC, TechQuery commented on package.json
>      }
放在 `dependencies`、`devDependencies` 之间

2023-05-03 13:00 UTC, TechQuery commented on source/types.d.ts
> +declare module '*.png';
```suggestion
declare module '*.png' {
    const path: string;

    export default path;
}
```

2023-05-03 13:00 UTC, TechQuery commented on tsconfig.build.json
> +        "declaration": true
```suggestion
        "declaration": true,
        "emitDeclarationOnly": true,
        "noEmit": false,
        "outDir": "dist"
```

2023-05-03 13:00 UTC, TechQuery commented on .storybook/main.ts
> +                    prettierConfig: { printWidth: 80, singleQuote: false }
把 `package.json` 里的相关配置移到 `prettier.config.js` 中，再 `import` 进来并赋值，参见：
https://prettier.io/docs/en/configuration.html

2023-05-03 13:00 UTC, TechQuery commented on .storybook/preview.ts
> +        // },
这里是什么情况？

2023-05-03 13:00 UTC, TechQuery commented on stories/Avatar.stories.ts
> +type Story = StoryObj<typeof Avatar>;
```suggestion
export default meta;

type Story = StoryObj<typeof Avatar>;
```

2023-05-03 13:00 UTC, TechQuery commented on vite.config.ts
> +                    }
挨个确定一下 `window` 对象上的全局对象名：

![image](https://user-images.githubusercontent.com/19969570/235922747-5ecd2e9c-f37e-4df8-af25-dd806227b523.png)

2023-05-11 15:08 UTC, stevending1st commented on .storybook/preview.ts
> +        // },
参数类型，还是加回来吧，可以自动生成一些。

2023-05-26 19:48 UTC, TechQuery approved these changes

2023-05-26 19:49 UTC, merged

2023-06-09 07:35 UTC, TechQuery commented
Vite bundles `import()` into UMD without async loading, which is different with ESM:

## Source code

https://github.com/idea2app/Idea-React/blob/1ef0e5bc3daef408bb013cff381a1941d16e4304/source/OpenMap/index.tsx#L19

## Next.js 12 error

```text
Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///D:/Work/idea2app/IdeaMall/PWA/node_modules/.pnpm/leaflet@1.9.4/node_modules/leaflet/dist/leaflet-src.js (230:19)
<unknown>
file:///D:/Work/idea2app/IdeaMall/PWA/node_modules/.pnpm/leaflet@1.9.4/node_modules/leaflet/dist/leaflet-src.js (7:66)
Object.<anonymous>
file:///D:/Work/idea2app/IdeaMall/PWA/node_modules/.pnpm/leaflet@1.9.4/node_modules/leaflet/dist/leaflet-src.js (10:3)
Module._compile
node:internal/modules/cjs/loader (1196:14)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1250:10)
Module.load
node:internal/modules/cjs/loader (1074:32)
Function.Module._load
node:internal/modules/cjs/loader (909:12)
Module.require
node:internal/modules/cjs/loader (1098:19)
require
node:internal/modules/cjs/helpers (108:18)
Object.<anonymous>
file:///D:/Work/idea2app/IdeaMall/PWA/node_modules/.pnpm/@react-leaflet+core@1.1.1_leaflet@1.9.4_react-dom@17.0.2_react@17.0.2/node_modules/@react-leaflet/core/cjs/dom.js (8:16)
```

## Bundle structure

![image](https://github.com/idea2app/Idea-React/assets/19969570/4170ab6a-5849-46b1-bfc0-11f8fd98b2a5)

## Possible solutions

1. https://babeljs.io/docs/babel-plugin-transform-modules-umd
2. https://vitejs.dev/guide/features.html#dynamic-import
3. https://stackoverflow.com/a/76303955
4. https://sambitsahoo.com/blog/vite-code-splitting-that-works.html