Add Storybook case
idea2app/Idea-React pull request #33
Opened 2023-05-29 09:22 UTC by stevending1st

2023-05-30 08:20 UTC, TechQuery requested changes

2023-05-30 08:20 UTC, TechQuery commented on stories/CodeBlock.stories.tsx
> +    },
```suggestion
    render: ({ language, children }) => <CodeBlock language={language}>{children}</CodeBlock>,
```

2023-05-30 08:20 UTC, TechQuery commented on stories/Icon.stories.ts
> +        onClick: () => console.log('Hello World')
```suggestion
```
不推荐在图标上直接加点击事件，在外面包一层按钮比较语义化。

2023-05-30 08:20 UTC, TechQuery commented on stories/IdeaDialog.stories.tsx
> +import { useState } from 'react';
```suggestion
import type { Meta, StoryObj } from '@storybook/react';
import { useState } from 'react';

import { IdeaDialog } from '../source/IdeaDialog';
```

2023-05-30 08:20 UTC, TechQuery commented on stories/IdeaDialog.stories.tsx
> +                    {...otherArgs}
```suggestion
    render: ({ children, onCancel, ...otherArgs }) => {
        const [showDialog, setShowDialog] = useState(false);

        return (
            <>
                <button onClick={() => setShowDialog(true)}>view</button>

                <IdeaDialog
                    show={showDialog}
                    centered
                    onCancel={() => setShowDialog(false)}
                    {...otherArgs}
```
有默认值应该是可以推导类型的

2023-05-30 08:20 UTC, TechQuery commented on stories/IdeaPopover.stories.tsx
> +                <>This is the content of popover.</>
```suggestion
    render: props => (
            <IdeaPopover {...props}>
                <button>view</button>
                This is the content of popover.
```

2023-05-30 08:20 UTC, TechQuery commented on stories/Select.stories.tsx
> +                    setValue(item);
```suggestion
                    setValue(item);
                    onChange?.(item);
```

2023-05-30 08:20 UTC, TechQuery commented on stories/Select.stories.tsx
> +    render: ({ value, onChange, ...otherArgs }) => {
`Story` 是不是一个可以传 props 的范型？

2023-05-30 08:20 UTC, TechQuery commented on stories/SpinnerButton.stories.ts
> +        animation: { control: 'select', options: ['border', 'grow'] }
```suggestion
        animation: { control: 'select', options: ['border', 'grow'] },
        disabled: { control: 'boolean' }
```

2023-05-30 08:20 UTC, TechQuery commented on stories/SpinnerButton.stories.ts
> +        animation: 'grow'
```suggestion
        animation: 'grow',
        loading: true
```

2023-05-30 15:21 UTC, stevending1st commented on stories/Select.stories.tsx
> +    render: ({ value, onChange, ...otherArgs }) => {
![image](https://github.com/idea2app/Idea-React/assets/23376142/7e52e410-de12-4805-83f9-2f5e282d04c8)

2023-05-31 04:15 UTC, TechQuery requested changes

2023-05-31 04:15 UTC, TechQuery commented on stories/Select.stories.tsx
> +import { useState } from 'react';
你配一下排序插件吧

2023-05-31 04:44 UTC, stevending1st commented on stories/Select.stories.tsx
> +import { useState } from 'react';
> 你配一下排序插件吧

计划下个 PR 配置 eslint

2023-05-31 05:18 UTC, TechQuery approved these changes

2023-05-31 05:19 UTC, merged