[feature] Replace storybook with react-live
idea2app/Idea-React pull request #55
Opened 2024-08-28 09:41 UTC by Soecka

[add] react live
[optimize] CodeExample component

- Closes #54

2024-08-28 09:46 UTC, Soecka commented
[unfinished] 
- state component live editor
	1. `<Loading />` Component
	2. `<Select />` Component
	3. `<Dialog />` Component
	4. `<PageNav />` Component

2024-08-28 11:36 UTC, TechQuery requested changes

2024-08-28 11:36 UTC, TechQuery commented on preview/content.tsx
> +                    style={{ zIndex: '1040' }}
```suggestion
    toggle = async () => {
        this.showLoading = true;
        await sleep(1);
        this.showLoading = false;
    };

    render() {
        const { showLoading } = this;

        return (
            <>
                <Button
                    style={{ zIndex: '1040' }}
                    onClick={this.toggle}
```

2024-08-28 11:36 UTC, TechQuery commented on preview/content.tsx
> +                            </>
和下面那个组件有啥区别呢？

2024-08-28 11:36 UTC, TechQuery commented on .gitpod.yml
> +      command: pnpm run start
复用其它前端脚手架的同名文件内容，设置更详细。

2026-04-29 23:07 UTC, TechQuery commented
Replaced with #63

2026-04-29 23:07 UTC, closed without merging